export const services = [
  "BOOK DOMESTIC",
  "BOOK COMMERCIAL",
  "NDIS/TAC/DVA/WORKSAFE",
  "OVEN CLEANING",
  "WINDOW CLEANING",
  "END OF LEASE CLEANING",
  "STRATA CLEANING",
  "PRESSURE WASHING",
  "GUTTER CLEANING",
  "GARDEN MAINTENANCE"
];
